### ISSUE TITLE
Error in response to storage.get: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by fi5er** [Pauan/AutoScroll#1]
As of a few hours ago, AutoScroll (installed via Chrome store) has stopped working here. The installed and recently updated version is 4.1_0, the full error message in the console is

> Error in response to storage.get: TypeError: undefined is not a function
> at chrome-extension://occjjkgifpmdgodlplnacmkejpdionan/data/AutoScroll.js:4:22

The code in question is

    chrome.storage.local.get(defaults, function (options) {
                         ^

It's possible that my version of Chromium (v34, which is admittedly quite old) is simply no longer supported, but the Changelog only says *"Removed support for extremely old versions of Chrome (version 28 or older)"*. In that case, the `minimum_chrome_version` in the manifest should be bumped to the lowest supported version (and I'll have to go looking for an older version of this extension).

**Comment by Pauan** [comment]
Thanks for the report.

That doesn't make any sense, since AutoScroll has been using `chrome.storage.local.get` for years, so that doesn't explain why it stopped working recently.

In addition, the `chrome.storage` API has been available since Chrome version 20, making it even stranger.

And unfortunately, I don't have access to old versions of Chrome, so it'll be hard to figure out what the problem is.

I understand you have your reasons for using an old version of Chrome, but in the long run it will benefit you to upgrade to a semi-recent version.

If you want, I can try giving you some code that you can run, that way we can figure out together what the issue is.

**Comment by fi5er** [comment]
I am unfortunately restricted to Chrome 34 for a while yet, and I completely understand that backward compatibility with outdated browsers can't be a priority - especially with Chrome's forced automatic updates. Not many people will be affected by this, so closing the issue would be perfectly understandable.

Meanwhile, I've done a little testing... Using the VMs provided by BrowserStack, I've found out that starting with Chrome 35 and up, everything works fine again. BrowserStack doesn't provide Linux images, so I did the tests on Windows 8.1 (and using AutoScroll 4.2 this time), but the error message on Chrome 34 was identical.

Interestingly, Chrome 33 also failed, but with a different error message:

> Error in response to storage.get: TypeError: Object #<HTMLDivElement> has no method 'createShadowRoot'
> at chrome-extension://occjjkgifpmdgodlplnacmkejpdionan/data/AutoScroll.js:4:22

Note that the line and column of the error as shown in the console is the same as before. It now seems unlikely that any of the two errors actually have anything to do with the `chrome.storage` API; they must be triggered somewhere inside the callback function.

**Comment by fi5er** [comment]
I have no experience with debugging Chrome extensions. I might try inserting a few strategic `console.log()` statements to pinpoint the source, if you're interested. Or I could just revert to the version before (if it's available from GitHub).

**Comment by Pauan** [comment]
Yeah, you're right, the shadow DOM is supported by Chrome 35 and up.

It seems odd to me that the line numbers would be completely wrong, but then again it is a very old version, so I guess it's not too surprising that the debugging would be worse in older versions.

I just released version 4.4, which should fix it so that AutoScroll will work in Chrome versions 29 to 34. Please try it and tell me if it works for you now.

**Comment by fi5er** [comment]
Works perfectly on Chrome 34. The error on Chrome 33 is also gone.

Thank you very much for spending the time to fix such a niche issue. I've come to depend on AutoScroll more than I'd realized, glad to have it back :)

**Comment by Pauan** [comment]
Great. Thanks for your help in solving the issue. The error messages were very helpful.
